### ISSUE TITLE
Notice This transaction would have succeeded, but was rolled back by a supplied post-condition.🐞[BUG] 

### ISSUE THREAD

**Issue by Elyalfa** [citycoins/citycoin-ui#170] opened 2023-11-22 18:47 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by eric-hendrickson** [comment] 2023-12-02 00:04
Appears to be a duplicate of #167

**Comment by whoabuddy** [comment] 2023-12-17 06:37
Closing out as it's just an issue template.

**Closed as completed by whoabuddy** 2023-12-17 06:37 UTC
Labels: Bug
